sudo: false

os:
  - linux

dist: xenial

language: python

env:
  - TEST_SUITE=unit
  - TEST_SUITE=integration

matrix:
  include:
  - name: "Unit Test"
    python: "3.6"
    env: TEST_SUITE=unit
  - name: "Integration Tests"
    python: "3.6"
    env: TEST_SUITE=integration

cache: pip

services:
  - xvfb

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install --file conda_requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install

script: python ./bin/test pep8 cov $TEST_SUITE

after_success:
  - codecov

notifications:
  email: false
