sudo: false

language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh -O conda.sh
  - bash conda.sh -b -p $HOME/conda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - pip install -r test_requirements.txt
  - python setup.py install

script:
  - python ./bin/test pep8 cov

after_success:
  - codecov

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
