language: python

sudo: false

python:
- '3.3'
- '3.4'

addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - python-pip
      - python-virtualenv

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- pip install -r test_requirements.txt
- python setup.py install

script:
- ./bin/test pep8 cov

after_success:
- codecov

deploy:
  provider: pypi
  user: jgostick
  password:
    secure: cCglX1NDCf/dkWeqmMZ0wYGi33FoGKYNSYBMVdS3LhpfsQ3+wCYzP/1uw8mM1KsHI9kAe+MOpQmxCe6ryt6/Y5DpFMqzbfMjaMI/PvYO7NhPDeJzYIJ4Mq1LCPGbFih8eMej7aLd/jLK4fiJtA3PUs1vRJCWOgRxHw5+DWhJBWw=
  on:
    tags: true
    branch: master
