language: python

cache:
  directories:
    - $HOME/.cache/pip

sudo: false

python:
- '3.4'

addons:
  apt:
    packages:
    - python3-matplotlib
    - libatlas-base-dev
    - gfortran

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pip install --upgrade pip
- mkdir -p $HOME/.cache/pip/wheels
# build wheel only if none present
- travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
# now install from it
- pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy

install:
- pip install -r test_requirements.txt
- python3 setup.py install

script:
- ./bin/test pep8 cov

after_success:
- codecov

deploy:
  provider: pypi
  user: jgostick
  password:
    secure: cCglX1NDCf/dkWeqmMZ0wYGi33FoGKYNSYBMVdS3LhpfsQ3+wCYzP/1uw8mM1KsHI9kAe+MOpQmxCe6ryt6/Y5DpFMqzbfMjaMI/PvYO7NhPDeJzYIJ4Mq1LCPGbFih8eMej7aLd/jLK4fiJtA3PUs1vRJCWOgRxHw5+DWhJBWw=
  on:
    tags: true
    branch: master
